version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: spa_salon
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spa-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - spa-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "50053:50053"
    depends_on:
      - postgres
    networks:
      - spa-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "50052:50052"
    depends_on:
      - postgres
    networks:
      - spa-network

  news-service:
    build:
      context: ./news-service
    container_name: news-service
    ports:
      - "50054:50054"
    depends_on:
      - postgres
    networks:
      - spa-network

  gateway:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "82:82"
    depends_on:
      - auth-service
      - product-service
      - user-service
      - news-service
    networks:
      - spa-network

volumes:
  postgres_data:

networks:
  spa-network:
    driver: bridge
